---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-operator
  name: tf-job-operator
  namespace: kube-queue
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: tf-job-dashboard
  name: tf-job-dashboard
rules:
  - apiGroups:
      - tensorflow.org
      - kubeflow.org
    resources:
      - tfjobs
      - tfjobs/status
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - pods/log
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: tf-job-operator
  name: tf-job-operator
rules:
  - apiGroups:
      - tensorflow.org
      - kubeflow.org
    resources:
      - tfjobs
      - tfjobs/status
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: tf-job-operator
  name: tf-job-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-job-operator
subjects:
  - kind: ServiceAccount
    name: tf-job-operator
    namespace: kube-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-job-operator
  namespace: kube-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: tf-job-operator
  template:
    metadata:
      labels:
        kustomize.component: tf-job-operator
        name: tf-job-operator
    spec:
      containers:
        - command:
            - /opt/tf-operator.v1
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: registry.cn-hangzhou.aliyuncs.com/kubernetes-image-hub/tf-operator:1.1.0-eb01d93b
          name: tf-job-operator
      serviceAccountName: tf-job-operator
